# Syncthing - continuous file synchronization
# https://docs.syncthing.net/
configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8384"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  tailscale-syncthing:
    image: tailscale/tailscale:latest
    container_name: tailscale-syncthing
    hostname: syncthing
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234
      - TS_AUTH_ONCE=true
    configs:
      - source: ts-serve
        target: /config/serve.json
    volumes:
      - ../../tailscale/syncthing/ts-config:/config
      - ../../tailscale/syncthing/ts-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:latest
    network_mode: service:tailscale-syncthing
    environment:
      TZ: 'Europe/Amsterdam'
      STGUIADDRESS: '0.0.0.0:8384'
    volumes:
      # Syncthing configuration
      - ../../data/syncthing/config:/var/syncthing/config
      # Synced files folder
      - ../../data/syncthing/sync:/var/syncthing/sync
    depends_on:
      tailscale-syncthing:
        condition: service_healthy
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
